data:
  source_url: "https://download.pytorch.org/tutorial/hymenoptera_data.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages
  model_dir: model
  init_model_file: model.pth
  trained_model_file: model.pth

params:
  img_shape: [224,224,3]
  lr: 0.001
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  validation_split: 0.2
  batch_size: 32
  seed: 42
  buffer_size: 32
  epochs: 10